plugins { id 'com.android.application' }
android {
    namespace 'com.willcreations.harness'
    compileSdk 35
    defaultConfig {
        applicationId 'com.willcreations.harness.stable'
        minSdk 30
        targetSdk 35
        versionCode 8
        versionName '0.8.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures { aidl true }
}

dependencies {
    def shizukuVersion = '13.1.5'
    implementation "dev.rikka.shizuku:api:$shizukuVersion"
    implementation "dev.rikka.shizuku:provider:$shizukuVersion"
    implementation "com.termux.termux-app:termux-shared:0.118.0"
    implementation "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"
    testImplementation 'junit:junit:4.13.2'
}
